# Generated by Django 4.2.6 on 2023-10-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_applied_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.URLField(),
        ),
    ]
