# Generated by Django 4.2.6 on 2023-10-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_job_pathway'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Seattle', max_length=50),
        ),
    ]
