# Generated by Django 4.2.6 on 2023-11-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='See Post', max_length=5000),
        ),
    ]
